/**
 * constants.js — all shared server-side constants
 * No magic strings in controllers or services; import from here.
 */

const DOMAINS = ['Benefits', 'Tax'];
const FREQUENCIES = ['Daily', 'Weekly', 'Monthly', 'Ad-hoc'];
const STATUSES = ['Success', 'Failed', 'Running', 'Skipped'];
const ENVIRONMENTS = ['DEV', 'QA', 'PROD'];

/** Derived "active" status for summary cards */
const ACTIVE_STATUSES = ['Success', 'Running'];

/**
 * Complete approved list of Schedule Name / Job Group Name values.
 * Rows whose scheduleName is NOT in this set are loaded but flagged with
 * scheduleValid: false so the UI can show a warning badge.
 */
const VALID_SCHEDULE_NAMES = new Set([
  'MSAccess_reports_saturday_4am',
  'annual_recon_clearance_check_sch',
  'appeals_reports_145pm',
  'appeals_reports_615pm',
  'appeals_reports_830am',
  'benefits_biweekly_day_5am',
  'benefits_daily_0630pm',
  'benefits_daily_1030am',
  'benefits_daily_1140pm',
  'benefits_daily_11pm',
  'benefits_daily_12pm',
  'benefits_daily_12pm_top',
  'benefits_daily_3pm',
  'benefits_daily_4pm',
  'benefits_daily_515pm',
  'benefits_daily_5_15am',
  'benefits_daily_5am',
  'benefits_daily_5am_withHoliday',
  'benefits_daily_6am',
  'benefits_daily_730am',
  'benefits_daily_7am',
  'benefits_daily_815am',
  'benefits_daily_8am',
  'benefits_daily_915am',
  'benefits_daily_915pm',
  'benefits_daily_930am',
  'benefits_daily_930pm',
  'benefits_daily_9am',
  'benefits_daily_9pm',
  'benefits_daily_DCA_6am',
  'benefits_daily_sendtext_7am',
  'benefits_daily_sendtext_8am',
  'benefits_eb_monthly_10th_day_6am',
  'benefits_eb_qtrly_9th_day_530pm',
  'benefits_eb_weekly_sunday_3pm',
  'benefits_icon_export_10am',
  'benefits_icon_import_12pm',
  'benefits_monthly_10th_day_6am',
  'benefits_monthly_12th_day',
  'benefits_monthly_15th_day_6am',
  'benefits_monthly_17th_day',
  'benefits_monthly_1st_day_6am',
  'benefits_monthly_2nd_day',
  'benefits_monthly_2nd_monday_6am',
  'benefits_monthly_3rd_day_6am',
  'benefits_monthly_5th_day_9am',
  'benefits_monthly_6th_day_9am',
  'benefits_monthly_8th_day_6am',
  'benefits_monthly_8th_day_7pm',
  'benefits_monthly_9th_day_6am',
  'benefits_monthly_last_day_7pm',
  'benefits_peuc_qtrly_9th_day_530pm',
  'benefits_peuc_weekly_sunday_3pm',
  'benefits_qtrly_10th_day',
  'benefits_qtrly_15th_day',
  'benefits_qtrly_1st_day',
  'benefits_qtrly_1st_day_4_am',
  'benefits_qtrly_1st_day_of_3rd_Month',
  'benefits_qtrly_20th_day',
  'benefits_qtrly_20th_day_2nd_Month',
  'benefits_qtrly_3rd_day_1st_month_9am',
  'benefits_qtrly_5th_work_day',
  'benefits_qtrly_9th_day',
  'benefits_qtrly_9th_day_530pm',
  'benefits_qtrly_last_day_3pm',
  'benefits_qtrly_last_day_of_first_month',
  'benefits_qtrly_third_month_15th',
  'benefits_reports_7am',
  'benefits_sat_4am',
  'benefits_temp_claim_8pm',
  'benefits_tue_sat_6am',
  'benefits_weekly_1st_work_day330pm',
  'benefits_weekly_1st_work_day_7am',
  'benefits_weekly_friday_10pm',
  'benefits_weekly_friday_4pm',
  'benefits_weekly_friday_6am',
  'benefits_weekly_friday_730am',
  'benefits_weekly_friday_830pm',
  'benefits_weekly_friday_9pm',
  'benefits_weekly_monday_10am',
  'benefits_weekly_monday_515pm',
  'benefits_weekly_monday_6am',
  'benefits_weekly_saturday_6am',
  'benefits_weekly_saturday_8pm',
  'benefits_weekly_saturday_9pm',
  'benefits_weekly_sunday_1230am',
  'benefits_weekly_sunday_12pm',
  'benefits_weekly_sunday_3pm',
  'benefits_weekly_sunday_6pm',
  'benefits_weekly_sunday_9pm',
  'benefits_weekly_thursday_10pm',
  'benefits_weekly_thursday_12pm',
  'benefits_weekly_thursday_2pm',
  'benefits_weekly_thursday_9am',
  'benefits_weekly_tuesday_11am',
  'benefits_weekly_tuesday_5pm',
  'benefits_weekly_tuesday_6am',
  'benefits_weekly_wednesday_1030am',
  'benefits_weekly_wednesday_10am',
  'benefits_weekly_wednesday_6am',
  'corr_appeals',
  'corr_benefits',
  'corr_bpc_tra',
  'corr_dms',
  'corr_dms_morningrun',
  'corr_nonmon',
  'corr_webservice_twice_daily',
  'email_daily_2pm',
  'email_daily_5am',
  'eta_2nd_thursday_of_2ndMonth_of_quarter',
  'monthly_1st_Sunday',
  'monthly_1st_sunday',
  'on_demand',
  'reports_annual_july_1st',
  'reports_sat_7am',
  'special_holiday_12pm',
  'special_holiday_6pm',
  'top_annual_wednesday_12pm',
  'top_recert',
  'user_stat',
  'workflow_reports_530am',
  'workflow_reports_6am',
  'xmatch_1st_thursday_of_2ndMonth_of_quarter',
  'xmatch_2nd_thursday_of_1stMonth_of_quarter',
]);

module.exports = { DOMAINS, FREQUENCIES, STATUSES, ENVIRONMENTS, ACTIVE_STATUSES, VALID_SCHEDULE_NAMES };
